=== erhaowww/Online-Used-Car-Selling-Website/database/xml/delivery.dtd
<!ELEMENT delivery (car*)>
<!ELEMENT car (payment_id, delivery_date, delivery_status)>
<!ELEMENT payment_id (#PCDATA)>
<!ELEMENT delivery_date (#PCDATA)>
<!ELEMENT delivery_status (#PCDATA)>

=== erhaowww/Online-Used-Car-Selling-Website/database/xml/delivery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE delivery SYSTEM "delivery.dtd">
<delivery>
<car><payment_id>128</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Delayed</delivery_status></car><car><payment_id>129</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Delivered</delivery_status></car><car><payment_id>130</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>in Transit</delivery_status></car><car><payment_id>131</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Ready for Pickup</delivery_status></car><car><payment_id>132</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>on Hold</delivery_status></car><car><payment_id>133</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Prepare to Ship</delivery_status></car><car><payment_id>134</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Ready for Pickup</delivery_status></car><car><payment_id>135</payment_id><delivery_date>2023-05-05</delivery_date><delivery_status>Prepare to Ship</delivery_status></car><car><payment_id>136</payment_id><delivery_date>2023-05-15</delivery_date><delivery_status>Prepare to Ship</delivery_status></car><car><payment_id>137</payment_id><delivery_date>2023-05-16</delivery_date><delivery_status>Delivered</delivery_status></car><car><payment_id>138</payment_id><delivery_date>2023-05-16</delivery_date><delivery_status>Prepare to Ship</delivery_status></car></delivery>
