=== erhaowww/Online-Used-Car-Selling-Website/database/xml/sellers.dtd
<!ELEMENT sellers (seller*)>
<!ELEMENT seller (seller_id, car)>
<!ELEMENT seller_id (#PCDATA)>
<!ELEMENT car (make, model, year, mileage, color, transmission, description, image, price, buyer)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT transmission (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT buyer (name, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST seller_id
    ID CDATA #REQUIRED>

<!ATTLIST image
    type CDATA #REQUIRED>

<!ATTLIST buyer
    payment CDATA #REQUIRED>

=== erhaowww/Online-Used-Car-Selling-Website/database/xml/sellers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sellers SYSTEM "sellers.dtd">
<sellers>
  <seller><seller_id>28</seller_id><car><make>Mercedes-Benz</make><model>A250</model><year>2014</year><mileage>56802</mileage><color>black</color><transmission>auto</transmission><description>The Mercedes-Benz A250 is a luxurious compact car that offers a perfect blend of sportiness and elegance.</description><image>13450703506454bc2b9fea7.png</image><price>112600</price><buyer><name>bronze</name><email>bronze@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Honda</make><model>Accord i-VTEC VTi-L 2.0</model><year>2016</year><mileage>118701</mileage><color>gray</color><transmission>auto</transmission><description>The Honda Accord i-VTEC VTi-L 2.0 is a mid-size sedan that offers a comfortable and refined driving experience.</description><image>6660698946454be067d1f2.png</image><price>81000</price><buyer><name>silver</name><email>silver@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Proton</make><model>X70</model><year>2019</year><mileage>64891</mileage><color>silver</color><transmission>auto</transmission><description>The Proton X70 is a mid-size sport utility vehicle (SUV) manufactured by the Malaysian automaker, Proton.</description><image>17224361326454bd219082d.png</image><price>84400</price><buyer><name>silver</name><email>silver@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Ford</make><model>Ranger Raptor High Rider 2.0</model><year>2019</year><mileage>650997</mileage><color>blue</color><transmission>auto</transmission><description>The Ford Ranger Raptor High Rider 2.0 is a powerful pick-up truck designed for off-road adventures.</description><image>1833655446454b179eeb5f.png</image><price>155400</price><buyer><name>gold</name><email>gold@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>BMW</make><model>X5</model><year>2017</year><mileage>72542</mileage><color>white</color><transmission>auto</transmission><description>The BMW X5 xDrive40e M Sport 2.0 is a luxurious and sporty SUV that combines powerful performance with eco-friendly efficiency.</description><image>19690442796454bb83dbed7.png</image><price>149800</price><buyer><name>gold</name><email>gold@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Honda</make><model>Civic S</model><year>2018</year><mileage>90465</mileage><color>red</color><transmission>auto</transmission><description>The Honda Civic S is a variant of the Honda Civic, a popular compact car.</description><image>15761685236454c30a2746f.png</image><price>89800</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Honda</make><model>HR-V</model><year>2021</year><mileage>30972</mileage><color>red</color><transmission>auto</transmission><description>The Honda HR-V is a subcompact crossover SUV that offers a versatile and practical design suitable for urban driving.</description><image>596394866454bf638fa5c.png</image><price>99900</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Mazda</make><model>CX-5</model><year>2018</year><mileage>81753</mileage><color>red</color><transmission>auto</transmission><description>The Mazda CX-5 is a stylish and sporty compact crossover SUV with a refined interior and impressive driving dynamics.</description><image>1050975656454c02715555.png</image><price>119900</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Mazda</make><model>CX-3</model><year>2018</year><mileage>97057</mileage><color>blue</color><transmission>auto</transmission><description>The Mazda CX-3 is a subcompact crossover SUV that offers style, comfort, and performance in a compact package. It has a sporty exterior with sleek lines, aggressive headlights, and a bold front grille.</description><image>41790676454be848e043.png</image><price>91800</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Nissan</make><model>Navara PRO-4X</model><year>2021</year><mileage>13509</mileage><color>red</color><transmission>auto</transmission><description>The Nissan Navara PRO-4X is a tough and rugged pickup truck designed for off-road adventures.</description><image>16599140596454bfc76523b.png</image><price>129000</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Mazda</make><model>CX-3</model><year>2019</year><mileage>82636</mileage><color>red</color><transmission>auto</transmission><description>The Mazda CX-3 is a subcompact crossover SUV that offers a sleek and stylish design, athletic handling, and advanced safety features.</description><image>18981996256454c36721a55.png</image><price>99800</price><buyer><name>gold</name><email>gold@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>perodua</make><model>Bezza</model><year>2017</year><mileage>122860</mileage><color>Brown</color><transmission>Auto</transmission><description>THIS CAR IS GOOD</description><image>14176392976463248792827.png</image><price>39800</price><buyer><name>platinum</name><email>platinum@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Volkswagen</make><model>Tiguan 280 TSI Comfortline</model><year>2017</year><mileage>87077</mileage><color>black</color><transmission>auto</transmission><description>The Volkswagen Tiguan 280 TSI Comfortline is a compact SUV designed to provide a comfortable and enjoyable driving experience.</description><image>9619310626454c21a78dcf.png</image><price>86600</price><buyer><name>gold</name><email>gold@gmail.com</email></buyer></car></seller><seller><seller_id>28</seller_id><car><make>Ford</make><model>Ranger Wildtrak High Rider</model><year>2021</year><mileage>21334</mileage><color>black</color><transmission>manual</transmission><description>The Ford Ranger Wildtrak High Rider is a rugged pickup truck designed for off-road adventures and work on tough terrain.</description><image>5870221616454c1200e0da.png</image><price>133001</price><buyer><name>gold</name><email>gold@gmail.com</email></buyer></car></seller></sellers>
